---
- name: "Enable the extra repositories"
  yum: name={{ item }} state=present
  with_items:
    - https://packages.distributed-ci.io/dci-release.el7.noarch.rpm
    - https://www.rdoproject.org/repos/rdo-release.rpm
    - epel-release

# not ready yet
- yum: name=dci-agent state=present

- file: path=/etc/dci state=directory mode=0755
- template: src=dci_agent.yaml.j2 dest=/etc/dci/dci_agent.yaml
- template: src=prepare-tripleo-helper-config.sh.j2 dest=/usr/local/bin/prepare-tripleo-helper-config.sh mode=0755
- block:
    - file: path=/home/centos/html state=directory mode=0755
    - copy: src=id_rsa dest=/home/centos/.ssh/id_rsa mode=0600
    - copy: src=id_rsa.pub dest=/home/centos/.ssh/id_rsa.pub mode=0755
    - copy: src=known_hosts dest=/home/centos/.ssh/known_hosts mode=0644
    - template: src=openrc.sh.j2 dest=/home/centos/openrc.sh mode=0755
#    - shell: source /home/centos/openrc.sh && dci-agent
  become_user: centos
