---
- name: "Enable the extra repositories"
  yum: name={{ item }} state=present
  with_items:
    - https://packages.distributed-ci.io/dci-release.el7.noarch.rpm
    - https://www.rdoproject.org/repos/rdo-release.rpm
    - epel-release

- copy: src=dci-agent.rpm dest=/tmp/dci-agent.rpm mode=0600
- yum: name=/tmp/dci-agent.rpm state=present

- file: path=/etc/dci state=directory mode=0755
- file: path=/var/lib/dci-agent state=directory owner=dci-agent group=dci-agent mode=0755
- template: src=dci_agent.yaml.j2 dest=/etc/dci/dci_agent.yaml
- template: src=prepare-tripleo-helper-config.sh.j2 dest=/usr/local/bin/prepare-tripleo-helper-config.sh mode=0755
- file: path={{ item }} state=directory mode=0755 owner=dci-agent group=dci-agent
  with_items:
  - /var/lib/dci-agent/.ssh
  - /var/lib/dci-agent/.html
- file: path=/var/lib/dci-agent/html state=directory mode=0755 owner=dci-agent group=dci-agent
- copy: src=id_rsa dest=/var/lib/dci-agent/.ssh/id_rsa mode=0600 owner=dci-agent group=dci-agent
- copy: src=id_rsa.pub dest=/var/lib/dci-agent/.ssh/id_rsa.pub mode=0755 owner=dci-agent group=dci-agent
- copy: src=known_hosts dest=/var/lib/dci-agent/.ssh/known_hosts mode=0644 owner=dci-agent group=dci-agent
- template: src=openrc.sh.j2 dest=/var/lib/dci-agent/openrc.sh mode=0755 owner=dci-agent group=dci-agent
- service: name=dci-agent.timer enabled=yes state=started
- service: name=dci-agent.service enabled=yes
