---
- name: "Enable the extra repositories"
  yum: name={{ item }} state=present
  with_items:
    - https://packages.distributed-ci.io/dci-release.el7.noarch.rpm
    - https://www.rdoproject.org/repos/rdo-release.rpm
    - epel-release

- block:
    - copy: src={{ local_rpm_file }} dest=/tmp/local_rpm_file.rpm mode=0600
    - yum: name=/tmp/local_rpm_file.rpm state=present disable_gpg_check=yes
  when: local_rpm_file|d()
- yum: name=dci-agent state=present
- yum: name=httpd state=present
- service: name=httpd state=started
- file: path=/etc/dci state=directory mode=0755
- template: src=dci_agent.yaml.j2 dest=/etc/dci/dci_agent.yaml
- template: src=prepare-tripleo-helper-config.sh.j2 dest=/usr/local/bin/prepare-tripleo-helper-config.sh mode=0755
- file: path={{ item }} state=directory mode=0755 owner=dci-agent group=dci-agent
  with_items:
  - /var/lib/dci-agent/.ssh
  - /var/www/html
- copy: src=id_rsa dest=/var/lib/dci-agent/.ssh/id_rsa mode=0600 owner=dci-agent group=dci-agent
- copy: src=id_rsa.pub dest=/var/lib/dci-agent/.ssh/id_rsa.pub mode=0600 owner=dci-agent group=dci-agent
- copy: src=known_hosts dest=/var/lib/dci-agent/.ssh/known_hosts mode=0644 owner=dci-agent group=dci-agent
- copy: src=openrc.sh dest=/var/lib/dci-agent/openrc.sh mode=0755 owner=dci-agent group=dci-agent

# in order to be able to have a real time output of the deployment, we will
# continue without ansible
- template: src=run_dci_agent.sh.j2 dest=/tmp/run_dci_agent.sh mode=0755
  delegate_to: "localhost"
